### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jakerockland** [MetalKit/metal#5]
@mhorga is it possible to add a license to this repo please? 😄

**Comment by mhorga** [comment]
Done.

**Comment by jakerockland** [comment]
Awesome, thank you!

My name is Jake Rockland and I'm the former Vice President of the Delta Sigma Phi chapter at the University of Arizona. I’ve been working on a startup company with two friends of mine, and we just launched our crowdfunding campaign for Moment, our first product. We appreciate support of any kind - whether you buy the product, share it on social media, or give us feedback on anything we can do better. If you think we're doing something cool, I would really appreciate it if you would share this with your chapter.

Here is the link to check out our site: https://wearmoment.com

Thank you so much for your help!

Best,
Jake
